# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod "AFNetworking", "~> 2.0"
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Bugly'
pod 'UMengAnalytics'##标准SDK，含IDFA
pod 'TOWebViewController'




target 'oschinaPlus' do

end

target 'oschinaPlusTests' do

end

target 'oschinaPlusUITests' do

end

